Repository elastos/Elastos.ELA.SideChain, pull requests merged in 2019-03, with the labels that each got.

#223 move Prefix dependence from Ela/common to ELA/core/contract
  mempool/validator.go
  mempool/validator_test.go
  spv/service_test.go
Labels: ct-Refactor

#222 Add Services() to p2p server interface
  server/interface.go
  server/server.go
  service/common.go
  service/service.go
Labels: ct-NewFeature

#226 Fix peer msg type switch not working issue
  server/server.go
  server/server_test.go
Labels: ct-BugFix

#229 Release database iterator after use
  blockchain/chainstore.go
Labels: ct-BugFix

#228 Update server hanlePeerMsg unit test
  server/server_test.go
Labels: enhancement

#232 merge release v0.1.2 into dev
  blockchain/chainstore.go
  server/server.go
  server/server_test.go
Labels: merge

#231 merge release v0.1.2 into master
  auxpow/elafaker.go
  auxpow/sideauxpow.go
  blockchain/chainstore.go
  blockchain/log.go
  mempool/feehelper.go
  mempool/log.go
  mempool/validator.go
  mempool/validator_test.go
  netsync/log.go
  peer/log.go
  pow/log.go
  server/interface.go
  server/log.go
  server/server.go
  server/server_test.go
  service/common.go
  service/log.go
  service/service.go
  service/websocket/log.go
  service/websocket/server.go
  spv/log.go
  spv/service.go
  spv/service_test.go
  types/payload.go
  types/transaction.go
Labels: merge
